trigger:
- master

pr:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    curl https://sh.rustup.rs -sSf | sh -s -- -y
    echo "##vso[task.setVariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    echo "##vso[task.setVariable variable=cargoBinPath;]$HOME/.cargo/bin"
  displayName: 'Install Rust'

- task: DownloadPipelineArtifact@0
  displayName: 'Download cargo-kcov executable'
  inputs:
    pipelineId: 3209
    artifactName: 'kcov'
    targetPath: '$(cargoBinPath)'

- task: DownloadPipelineArtifact@0
  displayName: 'Download cargo-junit executable'
  inputs:
    pipelineId: 1369
    artifactName: 'cargo-junit'
    targetPath: '$(cargoBinPath)'

- script: |
    sudo chmod +rwx $(cargoBinPath)/kcov
    sudo chmod +rwx $(cargoBinPath)/cargo-kcov
    sudo chmod +rwx $(cargoBinPath)/cargo-junit
    mkdir -p $(Build.SourcesDirectory)/.testresults/unit
  displayName: 'Prep test tools'

- script: |
    set -eo pipefail
    cargo test --no-run
    # cargo kcov --kcov $(cargoBinPath)/kcov -o .coverage/unit --bin rusty-hook -- --exclude-pattern=$CARGO_HOME,/.cargo,_test.rs,main.rs,closures.rs
    cargo junit --name $(Build.SourcesDirectory)/.testresults/unit/junit.xml
    # sudo chmod +rw .coverage -R
    sudo chmod +rw .testresults -R
  displayName: 'Run tests'

# - script: |
#     bash <(curl -s https://codecov.io/bash) -t $(codecovToken)
#   displayName: 'Publish coverage to Codecov'

# - task: cobertura-transform@0
#   displayName: 'Transform Cobertura Format From 3 to 4'
#   inputs:
#     cobertura3FilePath: .coverage/unit/kcov-merged/cobertura.xml
#     cobertura4FilePath: .coverage/unit/kcov-merged/cobertura4.xml


# - task: PublishCodeCoverageResults@1
#   inputs:
#     codeCoverageTool: 'Cobertura'
#     summaryFileLocation: '$(Build.SourcesDirectory)/.coverage/unit/kcov-merged/cobertura4.xml'
#     reportDirectory: '$(Build.SourcesDirectory)/.coverage/unit/kcov-merged'
#   displayName: 'Publish coverage results'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: JUnit
    testResultsFiles: 'junit.xml'
    searchFolder: $(Build.SourcesDirectory)/.testresults/unit
    testRunTitle: 'nias::Unit Tests::Linux PR - Build $(Build.BuildId)'
  displayName: 'publish unit test results'
