trigger:
- master

pr:
- master

pool:
  vmImage: vs2017-win2016

steps:
- powershell: |
   Invoke-WebRequest -Uri 'https://win.rustup.rs' -Method 'GET' -OutFile .\rustup-init.exe
   .\rustup-init.exe -y
   echo "##vso[task.setVariable variable=PATH;]$env:PATH;$env:USERPROFILE\.cargo\bin"
   echo "##vso[task.setVariable variable=cargoBinPath;]$env:USERPROFILE\.cargo\bin"
  displayName: 'Install Rust'

- task: DownloadPipelineArtifact@0
  inputs:
    pipelineId: 1448
    artifactName: 'cargo-junit'
    targetPath: '$(cargoBinPath)'
  displayName: 'Download cargo-junit executable'

# This is basically a `cargo fetch` + compile, but includes dev deps as well.
# `cargo junit` will crash on Windows if the output includes fetch/compile info,
# hence running `cargo test` first.
- script: |
    cargo test --no-run
    mkdir $(Build.SourcesDirectory)\.testresults\unit
    cargo junit --name $(Build.SourcesDirectory)\.testresults\unit\junit.xml
  displayName: 'Run tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: JUnit
    testResultsFiles: 'junit.xml'
    searchFolder: $(Build.SourcesDirectory)/.testresults/unit
    testRunTitle: 'nias::Unit Tests::Windows PR - Build $(Build.BuildId)'
  displayName: 'Publish unit test results'
